// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCopa26.Data;

#nullable disable

namespace PortalCopa26.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615183318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PortalCopa26.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("PortalCopa26.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsMarcados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipacoesCopas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("PortalCopa26.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GolsMandante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoMandanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoVisitanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("SelecaoMandanteId");

                    b.HasIndex("SelecaoVisitanteId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("PortalCopa26.Models.RankingFifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pontuacao")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Posicao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId")
                        .IsUnique();

                    b.ToTable("RankingFifa");
                });

            modelBuilder.Entity("PortalCopa26.Models.Selecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BandeiraUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("GrupoId");

                    b.ToTable("Selecoes");
                });

            modelBuilder.Entity("PortalCopa26.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("PortalCopa26.Models.SimulacaoJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsMandante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GolsVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulacaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("SimulacaoId", "JogoId")
                        .IsUnique();

                    b.ToTable("SimulacaoJogos");
                });

            modelBuilder.Entity("PortalCopa26.Models.Jogador", b =>
                {
                    b.HasOne("PortalCopa26.Models.Selecao", "Selecao")
                        .WithMany("Jogadores")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selecao");
                });

            modelBuilder.Entity("PortalCopa26.Models.Jogo", b =>
                {
                    b.HasOne("PortalCopa26.Models.Grupo", "Grupo")
                        .WithMany("Jogos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PortalCopa26.Models.Selecao", "SelecaoMandante")
                        .WithMany()
                        .HasForeignKey("SelecaoMandanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalCopa26.Models.Selecao", "SelecaoVisitante")
                        .WithMany()
                        .HasForeignKey("SelecaoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("SelecaoMandante");

                    b.Navigation("SelecaoVisitante");
                });

            modelBuilder.Entity("PortalCopa26.Models.RankingFifa", b =>
                {
                    b.HasOne("PortalCopa26.Models.Selecao", "Selecao")
                        .WithOne("RankingFifa")
                        .HasForeignKey("PortalCopa26.Models.RankingFifa", "SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selecao");
                });

            modelBuilder.Entity("PortalCopa26.Models.Selecao", b =>
                {
                    b.HasOne("PortalCopa26.Models.Grupo", "Grupo")
                        .WithMany("Selecoes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("PortalCopa26.Models.SimulacaoJogo", b =>
                {
                    b.HasOne("PortalCopa26.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalCopa26.Models.Simulacao", "Simulacao")
                        .WithMany("Jogos")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("PortalCopa26.Models.Grupo", b =>
                {
                    b.Navigation("Jogos");

                    b.Navigation("Selecoes");
                });

            modelBuilder.Entity("PortalCopa26.Models.Selecao", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("RankingFifa");
                });

            modelBuilder.Entity("PortalCopa26.Models.Simulacao", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
